[TENJIN-14518] Update Flutter SDK with latest dependencies and native SDKs
tenjin/flutter-sdk pull request #8
Opened 2023-06-07 16:01 UTC by giraldogdiego

**JIRA**:

- https://adromance.atlassian.net/browse/TENJIN-14518

**Proposed Changes:**

- Update plugin with latest Tenjin SDKs
- Add missing methods
- Update Flutter, Android and iOS dependencies
- Use Maven and Cocoapods instead of binaries

**Steps:**

- [ ] Reviewed
- [ ] Deployed to Staging
- [ ] QA'd
- [ ] Deployed to Production

2023-06-07 20:06 UTC, nafeu requested changes
Some minor changes

2023-06-07 20:06 UTC, nafeu commented on android/src/main/kotlin/com/tenjin_sdk/TenjinSdkPlugin.kt
> +        transaction(call, result)
As pointed out by Colin, this should not be transaction(...)

2023-06-07 20:06 UTC, nafeu commented on README.md
> +  tenjin_plugin: any
Maybe use a fixed version or recommend a version alongside `any` being a possible option

2023-06-07 20:06 UTC, caleon commented on .idea/libraries/Flutter_Plugins.xml
> +</component>
need a newline

2023-06-08 15:21 UTC, caleon approved these changes

2023-06-09 15:53 UTC, merged